global:
    scrape_interval: 15s
    evaluation_interval: 15s
    external_labels:
        monitor: 'app-project'

scrape_configs:

    - job_name: 'prometheus'
      scrape_interval: 5s
      metrics_path: /metrics
      static_configs:
        - targets: ['localhost:9090']

    - job_name: 'traefik'
      scrape_interval: 5s
      metrics_path: /metrics
      static_configs:
        - targets:
            - traefik:8888

    - job_name: 'soketi'
      scrape_interval: 5s
      metrics_path: /metrics
      static_configs:
        - targets:
            - soketi:9601
