---
## DYNAMIC CONFIGURATION

tls:
    options:
        default:
            sniStrict: true
            minVersion: VersionTLS12
            cipherSuites:
                - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
                - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
                - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
                - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
                - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
                - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
                - TLS_AES_128_GCM_SHA256                    # TLS 1.3
                - TLS_AES_256_GCM_SHA384                    # TLS 1.3
                - TLS_CHACHA20_POLY1305_SHA256              # TLS 1.3
            curvePreferences:
                - CurveP521
                - CurveP384
