---
## DYNAMIC CONFIGURATION

http:

    services:

        webmin-svc:
            loadBalancer:
                passHostHeader: true
                servers:
                    - url: "http://host.docker.internal:9988"
