---
version: '3.9'

networks:
    app_network:
        external: true
        name: ${APP_DOCKER_NETWORK}

volumes:
    redis_data:

services:

    # docker exec -it company_redis redis-cli -n 0 -p 6379
    # 127.0.0.1:6379> AUTH "YOUR_REDIS_PASSWORD"
    redis:
        image: redis:7.0-alpine
        hostname: redis
        container_name: ${COMPOSE_PROJECT_NAME}_redis
        ports:
            - 6379
        cap_add:
            - SYS_RESOURCE
        volumes:
            - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
            - redis_data:/data
        command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--bind", "0.0.0.0"]
        networks:
            app_network:
        healthcheck:
            test: ["CMD-SHELL", "redis-cli -a \"YOUR_REDIS_PASSWORD\" --no-auth-warning ping | grep PONG"]
            start_period: 10s
            interval: 30s
            timeout: 5s
            retries: 3
